version: '3.8'

services:

  backend:
    build: ./betterave-backend
    networks:
      mynet:
        ipv4_address: 172.16.0.2
    environment:
      - API_KEY=BETTERAVEAPIKEY9999
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./betterave-backend:/app
      - ./database:/database
    ports: 
      - 5000:5000

  frontend:
    build: ./frontend
    networks:
      mynet:
        ipv4_address: 172.16.0.3
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.0.0/29
